export default {
  CHART: 'chart',
  PIVOT_GRID: 'pivot',
  DATA_GRID: 'grid',
  PIE_CHART: 'pie',
  CHOROPLETH: 'choropleth',
  TREEMAP: 'treeMap',
  LIQUID_FILL_GAUGE: 'liquidFillGauge',
  CARD: 'card',
  CALENDAR: 'calendar',
  BOX_PLOT: 'boxPlot',
  TEXT_BOX: 'textBox',
  TIMELINE: 'timeline',
  CHORD_DIAGRAM: 'chord',
  ARC_DIAGRAM: 'arc',
  WORDCLOUD: 'wordCloud',
  COORDINATE_LINE: 'coordinateLine',
  COORDINATE_DOT: 'coordinateDot',
  COLLAPSIBLE_TREE: 'collapsibleTree',
  RADIAL_TREE: 'radialTree',
  SUNBURST_CHART: 'sunburstChart',
  ZOOMABLE_CICLE: 'zoomableCicle',
  CICLE_PACKING: 'ciclePacking',
  SCATTER_PLOT: 'scatterPlot',
  FUNNEL_CHART: 'funnelChart',
  STAR_CHART: 'starChart'
};
