export const chartItemType = {
  bar: 'bar',
  stackedbar: 'stackedbar',
  fullstackedbar: 'fullstackedbar',
  rangeBar: 'rangeBar',
  scatter: 'scatter',
  line: 'line',
  stackedline: 'stackedline',
  fullstackedline: 'fullstackedline',
  stepline: 'stepline',
  spline: 'spline',
  area: 'area',
  stackedarea: 'stackedarea',
  fullstackedarea: 'fullstackedarea',
  steparea: 'steparea',
  splinearea: 'splinearea',
  stackedsplinearea: 'stackedsplinearea',
  fullstackedsplinearea: 'fullstackedsplinearea',
  bubble: 'bubble',
  sankey: 'sankey'
};
