const tempData = {
  'measures': [
    {
      'columns': [
        {
          'HIE_HIE_UNI_NM': '',
          'captionName': '매출액',
          'cubeId': 3674,
          'dataType': 'decimal',
          'expression': '',
          'folder': '',
          'format': '#,#',
          'hieFolderName': '',
          'isFolderType': false,
          'isLevelLeafType': false,
          'isLevelType': false,
          'isSnowFlakeType': false,
          'levelChildren': [],
          'logicalColumnName': '매출액',
          'logicalTableName': 'KRA_F_매출',
          'orderBy': '',
          'physicalColumnId': '',
          'physicalColumnName': '',
          'physicalTableName': '',
          'summaryType': 'Sum',
          'tableName': '[KRA_F_매출]',
          'type': 'measure',
          'uniqueName': '[KRA_F_매출].[매출액]',
          'visible': 1
        }
      ],
      'cubeId': 3674,
      'dsViewId': 3505,
      'logicalName': 'KRA_F_매출',
      'order': 1,
      'physicalName': 'KRA_F_매출',
      'type': '',
      'uniqueName': '[KRA_F_매출]',
      'visible': 1
    }
  ],
  'dimensions': [
    {
      'columns': [
        {
          'HIE_HIE_UNI_NM': '[KRA_D_일자].[기준년월일명]',
          'captionName': '매출일자',
          'cubeId': 3674,
          'dataType': 'varchar',
          'expression': '',
          'folder': '',
          'format': '',
          'hieFolderName': '',
          'isFolderType': false,
          'isLevelLeafType': false,
          'isLevelType': false,
          'isSnowFlakeType': false,
          'levelChildren': [],
          'logicalColumnName': '',
          'logicalTableName': '',
          'orderBy': 'Key Column                    ',
          'physicalColumnId': '기준년월일명',
          'physicalColumnName': '기준년월일명',
          'physicalTableName': 'KRA_D_일자',
          'summaryType': 'Count',
          'tableName': '[KRA_D_일자]',
          'type': 'dimension',
          'uniqueName': '[KRA_D_일자].[기준년월일명]',
          'visible': 1
        },
        {
          'HIE_HIE_UNI_NM': '[KRA_D_일자].[기준년월명]',
          'captionName': '매출년월',
          'cubeId': 3674,
          'dataType': 'varchar',
          'expression': '',
          'folder': '',
          'format': '',
          'hieFolderName': '',
          'isFolderType': false,
          'isLevelLeafType': false,
          'isLevelType': false,
          'isSnowFlakeType': false,
          'levelChildren': [],
          'logicalColumnName': '',
          'logicalTableName': '',
          'orderBy': 'Key Column                    ',
          'physicalColumnId': '기준년월명',
          'physicalColumnName': '기준년월명',
          'physicalTableName': 'KRA_D_일자',
          'summaryType': 'Count',
          'tableName': '[KRA_D_일자]',
          'type': 'dimension',
          'uniqueName': '[KRA_D_일자].[기준년월명]',
          'visible': 1
        },
        {
          'HIE_HIE_UNI_NM': '[KRA_D_일자].[기준년월일]',
          'captionName': '매출일자_달력',
          'cubeId': 3674,
          'dataType': 'char',
          'expression': '',
          'folder': '',
          'format': '',
          'hieFolderName': '',
          'isFolderType': false,
          'isLevelLeafType': false,
          'isLevelType': false,
          'isSnowFlakeType': false,
          'levelChildren': [],
          'logicalColumnName': '',
          'logicalTableName': '',
          'orderBy': 'Key Column                    ',
          'physicalColumnId': '기준년월일',
          'physicalColumnName': '기준년월일',
          'physicalTableName': 'KRA_D_일자',
          'summaryType': 'Count',
          'tableName': '[KRA_D_일자]',
          'type': 'dimension',
          'uniqueName': '[KRA_D_일자].[기준년월일]',
          'visible': 1
        },
        {
          'HIE_HIE_UNI_NM': '[KRA_D_일자].[기준년월]',
          'captionName': '매출년월_달력',
          'cubeId': 3674,
          'dataType': 'char',
          'expression': '',
          'folder': '',
          'format': '',
          'hieFolderName': '',
          'isFolderType': false,
          'isLevelLeafType': false,
          'isLevelType': false,
          'isSnowFlakeType': false,
          'levelChildren': [],
          'logicalColumnName': '',
          'logicalTableName': '',
          'orderBy': 'Key Column                    ',
          'physicalColumnId': '기준년월',
          'physicalColumnName': '기준년월',
          'physicalTableName': 'KRA_D_일자',
          'summaryType': 'Count',
          'tableName': '[KRA_D_일자]',
          'type': 'dimension',
          'uniqueName': '[KRA_D_일자].[기준년월]',
          'visible': 1
        }
      ],
      'cubeId': 3674,
      'dsViewId': 3505,
      'logicalName': 'KRA_D_일자',
      'order': 1,
      'physicalName': '[KRA_D_일자]',
      'type': '',
      'uniqueName': '[KRA_D_일자]',
      'visible': 1
    },
    {
      'columns': [
        {
          'HIE_HIE_UNI_NM': '[KRA_D_매표소].[매표소대명]',
          'captionName': '매표소대명',
          'cubeId': 3674,
          'dataType': 'varchar',
          'expression': '',
          'folder': '',
          'format': '',
          'hieFolderName': 'LEVEL_LEAF',
          'isFolderType': false,
          'isLevelLeafType': true,
          'isLevelType': false,
          'isSnowFlakeType': false,
          'levelChildren': [],
          'logicalColumnName': '',
          'logicalTableName': '',
          'orderBy': 'Key Column                    ',
          'physicalColumnId': '매표소대명',
          'physicalColumnName': '매표소대명',
          'physicalTableName': 'KRA_D_매표소',
          'summaryType': 'Count',
          'tableName': '[KRA_D_매표소]',
          'type': 'dimension',
          'uniqueName': '[KRA_D_매표소].[매표소대명]',
          'visible': 0
        },
        {
          'HIE_HIE_UNI_NM': '[KRA_D_매표소].[매표소소명]',
          'captionName': '매표소소명',
          'cubeId': 3674,
          'dataType': 'varchar',
          'expression': '',
          'folder': '',
          'format': '',
          'hieFolderName': 'LEVEL_LEAF',
          'isFolderType': false,
          'isLevelLeafType': true,
          'isLevelType': false,
          'isSnowFlakeType': false,
          'levelChildren': [],
          'logicalColumnName': '',
          'logicalTableName': '',
          'orderBy': 'Key Column                    ',
          'physicalColumnId': '매표소소명',
          'physicalColumnName': '매표소소명',
          'physicalTableName': 'KRA_D_매표소',
          'summaryType': 'Count',
          'tableName': '[KRA_D_매표소]',
          'type': 'dimension',
          'uniqueName': '[KRA_D_매표소].[매표소소명]',
          'visible': 0
        },
        {
          'HIE_HIE_UNI_NM': '[KRA_D_매표소].[HieLvl]',
          'captionName': 'KRA_D_매표소계층',
          'cubeId': 3674,
          'dataType': '',
          'expression': '',
          'folder': '',
          'format': '',
          'hieFolderName': 'LEVEL',
          'isFolderType': false,
          'isLevelLeafType': false,
          'isLevelType': true,
          'isSnowFlakeType': false,
          'levelChildren': [
            '[KRA_D_매표소].[매표소대명]',
            '[KRA_D_매표소].[매표소소명]',
            '[KRA_D_매표소].[매표소중명]'
          ],
          'logicalColumnName': '',
          'logicalTableName': '',
          'orderBy': 'Key Column                    ',
          'physicalColumnId': '',
          'physicalColumnName': '',
          'physicalTableName': '',
          'summaryType': 'Count',
          'tableName': '[KRA_D_매표소]',
          'type': 'dimension',
          'uniqueName': '[KRA_D_매표소].[HieLvl]',
          'visible': 1
        },
        {
          'HIE_HIE_UNI_NM': '[KRA_D_매표소].[매표소중명]',
          'captionName': '매표소_중분류',
          'cubeId': 3674,
          'dataType': 'varchar',
          'expression': '',
          'folder': '',
          'format': '',
          'hieFolderName': 'LEVEL_LEAF',
          'isFolderType': false,
          'isLevelLeafType': true,
          'isLevelType': false,
          'isSnowFlakeType': false,
          'levelChildren': [],
          'logicalColumnName': '',
          'logicalTableName': '',
          'orderBy': 'Key Column                    ',
          'physicalColumnId': '매표소중명',
          'physicalColumnName': '매표소중명',
          'physicalTableName': 'KRA_D_매표소',
          'summaryType': 'Count',
          'tableName': '[KRA_D_매표소]',
          'type': 'dimension',
          'uniqueName': '[KRA_D_매표소].[매표소중명]',
          'visible': 1
        }
      ],
      'cubeId': 3674,
      'dsViewId': 3505,
      'logicalName': 'KRA_D_매표소',
      'order': 2,
      'physicalName': '[KRA_D_매표소]',
      'type': '',
      'uniqueName': '[KRA_D_매표소]',
      'visible': 1
    },
    {
      'columns': [
        {
          'HIE_HIE_UNI_NM': '[KRA_D_경주코드].[경주명]',
          'captionName': '경주',
          'cubeId': 3674,
          'dataType': 'varchar',
          'expression': '',
          'folder': '',
          'format': '',
          'hieFolderName': '',
          'isFolderType': false,
          'isLevelLeafType': false,
          'isLevelType': false,
          'isSnowFlakeType': false,
          'levelChildren': [],
          'logicalColumnName': '',
          'logicalTableName': '',
          'orderBy': 'Key Column                    ',
          'physicalColumnId': '경주명',
          'physicalColumnName': '경주명',
          'physicalTableName': 'KRA_D_경주코드',
          'summaryType': 'Count',
          'tableName': '[KRA_D_경주코드]',
          'type': 'dimension',
          'uniqueName': '[KRA_D_경주코드].[경주명]',
          'visible': 1
        }
      ],
      'cubeId': 3674,
      'dsViewId': 3505,
      'logicalName': 'KRA_D_경주',
      'order': 3,
      'physicalName': '[KRA_D_경주코드]',
      'type': '',
      'uniqueName': '[KRA_D_경주코드]',
      'visible': 1
    }
  ]
};

export default tempData;
