/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.wise.MarketingPlatForm.report.domain.item.pivot.pivotmatrix.schema.avro;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class AvroSummaryParam extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 7684395082021486794L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"AvroSummaryParam\",\"namespace\":\"com.wise.MarketingPlatForm.report.domain.item.pivot.pivotmatrix.schema.avro\",\"fields\":[{\"name\":\"selector\",\"type\":[{\"type\":\"string\",\"avro.java.string\":\"String\"},\"null\"]},{\"name\":\"summaryType\",\"type\":[{\"type\":\"string\",\"avro.java.string\":\"String\"},\"null\"]}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<AvroSummaryParam> ENCODER =
      new BinaryMessageEncoder<AvroSummaryParam>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<AvroSummaryParam> DECODER =
      new BinaryMessageDecoder<AvroSummaryParam>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<AvroSummaryParam> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<AvroSummaryParam> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<AvroSummaryParam>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this AvroSummaryParam to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a AvroSummaryParam from a ByteBuffer. */
  public static AvroSummaryParam fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.String selector;
  @Deprecated public java.lang.String summaryType;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public AvroSummaryParam() {}

  /**
   * All-args constructor.
   * @param selector The new value for selector
   * @param summaryType The new value for summaryType
   */
  public AvroSummaryParam(java.lang.String selector, java.lang.String summaryType) {
    this.selector = selector;
    this.summaryType = summaryType;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return selector;
    case 1: return summaryType;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: selector = (java.lang.String)value$; break;
    case 1: summaryType = (java.lang.String)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'selector' field.
   * @return The value of the 'selector' field.
   */
  public java.lang.String getSelector() {
    return selector;
  }

  /**
   * Sets the value of the 'selector' field.
   * @param value the value to set.
   */
  public void setSelector(java.lang.String value) {
    this.selector = value;
  }

  /**
   * Gets the value of the 'summaryType' field.
   * @return The value of the 'summaryType' field.
   */
  public java.lang.String getSummaryType() {
    return summaryType;
  }

  /**
   * Sets the value of the 'summaryType' field.
   * @param value the value to set.
   */
  public void setSummaryType(java.lang.String value) {
    this.summaryType = value;
  }

  /**
   * Creates a new AvroSummaryParam RecordBuilder.
   * @return A new AvroSummaryParam RecordBuilder
   */
  public static com.wise.MarketingPlatForm.report.domain.item.pivot.pivotmatrix.schema.avro.AvroSummaryParam.Builder newBuilder() {
    return new com.wise.MarketingPlatForm.report.domain.item.pivot.pivotmatrix.schema.avro.AvroSummaryParam.Builder();
  }

  /**
   * Creates a new AvroSummaryParam RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new AvroSummaryParam RecordBuilder
   */
  public static com.wise.MarketingPlatForm.report.domain.item.pivot.pivotmatrix.schema.avro.AvroSummaryParam.Builder newBuilder(com.wise.MarketingPlatForm.report.domain.item.pivot.pivotmatrix.schema.avro.AvroSummaryParam.Builder other) {
    return new com.wise.MarketingPlatForm.report.domain.item.pivot.pivotmatrix.schema.avro.AvroSummaryParam.Builder(other);
  }

  /**
   * Creates a new AvroSummaryParam RecordBuilder by copying an existing AvroSummaryParam instance.
   * @param other The existing instance to copy.
   * @return A new AvroSummaryParam RecordBuilder
   */
  public static com.wise.MarketingPlatForm.report.domain.item.pivot.pivotmatrix.schema.avro.AvroSummaryParam.Builder newBuilder(com.wise.MarketingPlatForm.report.domain.item.pivot.pivotmatrix.schema.avro.AvroSummaryParam other) {
    return new com.wise.MarketingPlatForm.report.domain.item.pivot.pivotmatrix.schema.avro.AvroSummaryParam.Builder(other);
  }

  /**
   * RecordBuilder for AvroSummaryParam instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<AvroSummaryParam>
    implements org.apache.avro.data.RecordBuilder<AvroSummaryParam> {

    private java.lang.String selector;
    private java.lang.String summaryType;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.wise.MarketingPlatForm.report.domain.item.pivot.pivotmatrix.schema.avro.AvroSummaryParam.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.selector)) {
        this.selector = data().deepCopy(fields()[0].schema(), other.selector);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.summaryType)) {
        this.summaryType = data().deepCopy(fields()[1].schema(), other.summaryType);
        fieldSetFlags()[1] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing AvroSummaryParam instance
     * @param other The existing instance to copy.
     */
    private Builder(com.wise.MarketingPlatForm.report.domain.item.pivot.pivotmatrix.schema.avro.AvroSummaryParam other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.selector)) {
        this.selector = data().deepCopy(fields()[0].schema(), other.selector);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.summaryType)) {
        this.summaryType = data().deepCopy(fields()[1].schema(), other.summaryType);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'selector' field.
      * @return The value.
      */
    public java.lang.String getSelector() {
      return selector;
    }

    /**
      * Sets the value of the 'selector' field.
      * @param value The value of 'selector'.
      * @return This builder.
      */
    public com.wise.MarketingPlatForm.report.domain.item.pivot.pivotmatrix.schema.avro.AvroSummaryParam.Builder setSelector(java.lang.String value) {
      validate(fields()[0], value);
      this.selector = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'selector' field has been set.
      * @return True if the 'selector' field has been set, false otherwise.
      */
    public boolean hasSelector() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'selector' field.
      * @return This builder.
      */
    public com.wise.MarketingPlatForm.report.domain.item.pivot.pivotmatrix.schema.avro.AvroSummaryParam.Builder clearSelector() {
      selector = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'summaryType' field.
      * @return The value.
      */
    public java.lang.String getSummaryType() {
      return summaryType;
    }

    /**
      * Sets the value of the 'summaryType' field.
      * @param value The value of 'summaryType'.
      * @return This builder.
      */
    public com.wise.MarketingPlatForm.report.domain.item.pivot.pivotmatrix.schema.avro.AvroSummaryParam.Builder setSummaryType(java.lang.String value) {
      validate(fields()[1], value);
      this.summaryType = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'summaryType' field has been set.
      * @return True if the 'summaryType' field has been set, false otherwise.
      */
    public boolean hasSummaryType() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'summaryType' field.
      * @return This builder.
      */
    public com.wise.MarketingPlatForm.report.domain.item.pivot.pivotmatrix.schema.avro.AvroSummaryParam.Builder clearSummaryType() {
      summaryType = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public AvroSummaryParam build() {
      try {
        AvroSummaryParam record = new AvroSummaryParam();
        record.selector = fieldSetFlags()[0] ? this.selector : (java.lang.String) defaultValue(fields()[0]);
        record.summaryType = fieldSetFlags()[1] ? this.summaryType : (java.lang.String) defaultValue(fields()[1]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<AvroSummaryParam>
    WRITER$ = (org.apache.avro.io.DatumWriter<AvroSummaryParam>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<AvroSummaryParam>
    READER$ = (org.apache.avro.io.DatumReader<AvroSummaryParam>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
